# renovate: datasource=docker depName=docker.io/library/alpine
FROM docker.io/library/alpine:3.23

ARG TARGETPLATFORM
ARG VERSION=latest

USER root
WORKDIR /app

#hadolint ignore=DL3018
RUN \
    apk add --no-cache \
        bash \
        ca-certificates \
        catatonit \
        postgresql17-client="${VERSION}"

COPY ./entrypoint.sh /entrypoint.sh

USER nobody:nogroup

ENTRYPOINT ["/usr/bin/catatonit", "--", "/entrypoint.sh"]
