---
# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: App Inventory
description: Return items from the apps directory in a JSON array

outputs:
  items:
    description: App Inventory
    value: ${{ steps.inventory.outputs.items }}

runs:
  using: composite
  steps:
    - name: App Inventory
      uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7.1.0
      id: inventory
      with:
        script: |
          const fs = require('fs');
          const path = require('path');

          function scanDirectory(dirPath) {
              try {
                  const entries = fs.readdirSync(dirPath, { withFileTypes: true });
                  const folderNames = entries
                      .filter((entry) => entry.isDirectory())
                      .map((entry) => entry.name);
                  return folderNames;
              } catch (error) {
                  core.setFailed(`Error reading directory ${dirPath}:`, error.message);
                  return [];
              }
          }

          const apps = scanDirectory(path.resolve(process.cwd(), 'apps'))
            .sort()
            .map(name => ({ name }));
          core.setOutput('items', JSON.stringify(apps));
